<?php
/**
 * Modulo Drupal JSON Web Service v0.01
 * Equipo Mario
*/

function modulo2_menu() {
$items = array();
$items['api/node'] = array(
    'title' => 'JSON',
'page callback' => 'modulo2_api',
'access arguments' => array('access content')
);

return $items;
}


function modulo2_api($nid = null) {
    if($nid) {
        drupal_json_output(node_load($nid));
        drupal_exit();
    }
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
        ->propertyCondition('status', 1)
        ->propertyOrderBy('created', 'DESC')
        ->range(0, 5);

    $results = $query->execute();
    $nids = array_keys($results['node']);
    $nodes = node_load_multiple($nids);
    drupal_json_output($nodes);
    drupal_exit();
}